[gcp_service_account]
type = "service_account"
project_id = "ck-custom-examination"
private_key_id = "71511a322dd2faa799a51d523c24e416ea9bef3e"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDTgP4uXAKebSNV
qpnlXSRYbv18a85GEl7S3UkK1eiAPVgFtv7LJ4vgX+mjXnuthIhqeWVfnbgTtXuw
UZv+Jrhpbjxu6HpZwPiJp/fK/94itgEz5N1H+fIX1xPcWjFIKLkHPdnP8xzMIAP0
mMNOi64Ra11T9r6qsXobvbN80m5SL9dQiqWyHJ4gW+PPayXbFrTBIu+8eO0rVr9K
nnYXQMoj8DM41AamTFaS3Uv2IXpjQ90M1AWmpFBGSY3we8CfBcgllNgayFKG/YzUp
Itm5676Zcl5do/yJLysubG4CkCq5GbfnwZ/5yN1L9Uv4+OCkLScxHePL/VEw7muY
uECdEe4HAgMBAAECggEAOnsbTSRB0R5qO8CtRt9HMnCWBHYmlfd0YqevD6Dv5a2Q
jhv4PaIUqhi7GGICnorb0Vz5q8OHZ2Ox7KHUGSUJrpU9foknc3PJBP79pBK1kDF1
Ca1JhiJVT0Q4CKCjqckgyCDQ/g/BsatUjKhEsI4stkJSjunV9IqYMd11KJliybRS
DYZymL4izjLkYuH7I+3JzL5QWIcPFneVBdhMbeZJpSnVS7gTH8lnzhryIims88Bj
wifQmRzF16/9YRXdEa/d3XpGvmCsrGutcIMK6NA7DUtjZjJuPuIQMxRh+a9dgZVD
mlW4YPgD5n+zUI3DIHIyQVRLd5q/1en5b62SgaSHwQKBgQDpV2s5sgmzXfCkX9Ao
flossCF3DSiQpztSbpxF2SUPBP33e9AfRDKpAhAElqCPPzk2WyvTu9+q+8jspzee
qBcZlrNryYZHnTWmkKALlnWmeS5TFrmQ9m04leVA8vTnFFP+gMG5Rwk1F+v1jITV
5bll4P81Fp4ISv/nGoYLpEpboQKBgQDoCrfeDAPkWuYP2CuRVRg4oq81CBkWPVku
w5pCH6wpAnAR9x9Go/tUjBHu8NAIrFpyIrkNVMfOHtXSxNLv7G5z639Pcgz88uOa
UZXXwt8MKr3z1OWjkbxv1PhnuwH3eF+m9TMzhtJK8SZJdyHlgGaUIGeC5rrSunqc
0zMfYd8opwKBgGg0LONIGcLrObL+QsRCoNyCD3/N9Yab2AcY9FrQ/Ra3AP+LYEcG
OqV1EVgrOCqgbllS38CfjuQZqwHcLx+AK0i3HwsMpRXIJBRtU7u5BnNAfKqIZHhT
RDVX41hc53dmgZgPQfQOwBLgyvQOO6gV/fR8RRwdLJfBfoRjOOdsB/ThAoGBALb0
ZH7OKG9vgD/z6H4hgwR8uPpuVSFk46Fsln8Wa+61vllb6KwQ9UR3YFhuRQjhpDqj
yBaLxzJsu5kAmXSUjY4Wm32vZjA27mApfaTuQGFefgD31sw+Rz5BxE49c9KEdZ61
bFZvMfXm55I7PV2v/LFET3k1pQ4r/CsUlxViXMq3AoGBAOQVzCMFeaSkCqBuyI4F
nhX2sUthftg1VsjlEswZ0aXfjrCg51IKUwwc86WOLUfiF/eM1v3rm92/3YJdw2CD3
bJ9OWxgilaI0JnuLOiCOhTlNYcbiW9xvu13JKgKNGdAtQSHeSTR1T0FzIGKyjNJ7
52yox9sEojDwFZVc+KVzuNW7
-----END PRIVATE KEY-----'''
client_email = "ck-automation-sa@ck-custom-examination.iam.gserviceaccount.com"
client_id = "106702643581378507527"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ck-automation-sa%40ck-custom-examination.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
